#######################################################################################
# Book settings
title: TM Cafe

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

#######################################################################################
# Launch button settings
repository:
  url: https://github.com/makto-toruk/tm-cafe

#######################################################################################
# Exclude pages from build
exclude_patterns: [cafeenv/*]
